name: Docker

on:
  push:
    branches:
      - "main"
      - "master"
    tags:
      - "*"
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # To build images for multiple platforms
      - name: Set up QEMU for multi-platform images
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2.1.4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker metadata
        id: metadata
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: "${{ secrets.DOCKERHUB_USERNAME }}/garconne"
          tag-semver: |
            {{major}}
            {{major}}.{{minor}}
            {{major}}.{{minor}}.{{patch}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/386 # Requires setup-qemu-action
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: |
            ${{ steps.metadata.outputs.labels }}
            org.opencontainers.image.vendor=rgarrigue

      - name: Print image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      #
      # Docker Hub doesn't allow using a token, hence commenting out until https://github.com/peter-evans/dockerhub-description/issues/10 is fixed
      # - name: Update DockerHub repository description with README.md content
      #   uses: peter-evans/dockerhub-description@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     repository: "${{ secrets.DOCKERHUB_USERNAME }}/garconne"
